project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - All_Labs/lab1.qmd
  resources:
    - "tutorials/Lab1/www/*"
    - "tutorials/Lab1/images/*"
    - lab-interactions.js

website:
  title: "BIOS 2010 Labs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Labs
        menu:
          - href: All_Labs/lab1.qmd
            text: Lab 1

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body:
      - lab-interactions-root.html
    toc: true

editor: visual
